version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.94.0
    container_name: otel_collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    environment:
      - OTEL_ENVIRONMENT=${OTEL_ENVIRONMENT:-local}
    ports:
    networks:
      - text2sql_net
    depends_on:
      agent-control-db:
        condition: service_started
      minio:
        condition: service_healthy

networks:
  text2sql_net:
    external: true
