apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: agent-control-db:5432
    user: postgres
    database: agent_control
    jsonData:
      sslmode: "disable"
      postgresVersion: 1300
    secureJsonData:
      password: control_password
